import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { useLocation } from 'react-router-dom';

interface QuotesContextType {
  currentQuote: string;
  refreshQuote: () => void;
}

const QuotesContext = createContext<QuotesContextType | undefined>(undefined);

const COZY_QUOTES = [
  // Original quotes (1-205)
  "Every sunrise is an invitation to brighten someone's day.",
  "Small steps lead to big transformations.",
  "Be gentle with yourself; you're doing the best you can.",
  "The journey of a thousand miles begins with a single step.",
  "Your only limit is your mind.",
  "Embrace the glorious mess that you are.",
  "Breathe deeply. Live fully.",
  "Today is a gift. That's why it's called the present.",
  "You are enough, just as you are.",
  "Progress, not perfection.",
  "Let your light shine bright.",
  "Kindness is a language everyone understands.",
  "Trust the timing of your life.",
  "You are stronger than you think.",
  "Every moment is a fresh beginning.",
  "Choose joy, even in the small things.",
  "Your vibe attracts your tribe.",
  "Be the reason someone smiles today.",
  "Stars can't shine without darkness.",
  "Growth happens outside your comfort zone.",
  "You're not behind; you're exactly where you need to be.",
  "Inhale confidence, exhale doubt.",
  "Good things take time.",
  "Your potential is endless.",
  "Make today so awesome that yesterday gets jealous.",
  "Bloom where you are planted.",
  "The best is yet to come.",
  "You are capable of amazing things.",
  "Let go of what you can't change.",
  "Focus on the good.",
  "You matter more than you know.",
  "Dream big, start small, act now.",
  "Peace begins with a smile.",
  "Your story isn't over yet.",
  "Be patient with your progress.",
  "Sunshine mixed with a little hurricane.",
  "Create the life you can't wait to wake up to.",
  "You are the artist of your life.",
  "Keep going. Keep growing.",
  "Life is tough, but so are you.",
  "Find joy in the ordinary.",
  "You've survived 100% of your worst days.",
  "Be the energy you want to attract.",
  "One day at a time.",
  "You're doing better than you think.",
  "Let your dreams be bigger than your fears.",
  "Stay close to what keeps you feeling alive.",
  "Your future self is cheering you on.",
  "Make peace with your broken pieces.",
  "You deserve your own love.",
  "Every day is a second chance.",
  "Happiness blooms from within.",
  "You are worthy of all good things.",
  "Keep your face toward the sunshine.",
  "The world needs your unique light.",
  "Be stubborn about your goals.",
  "Self-care is not selfish.",
  "You are your only competition.",
  "Celebrate every tiny victory.",
  "You're allowed to take up space.",
  "Magic happens when you believe.",
  "Your energy introduces you before you speak.",
  "Be brave enough to be bad at something new.",
  "You're growing, even if you can't see it.",
  "Rest is productive too.",
  "Your heart knows the way.",
  "Keep planting seeds of kindness.",
  "You are a work of art in progress.",
  "Let your soul shine.",
  "Difficult roads lead to beautiful destinations.",
  "You are loved more than you know.",
  "Take life one cup of coffee at a time.",
  "Your comfort zone is beautiful but nothing grows there.",
  "Be unapologetically yourself.",
  "The sun will rise and we will try again.",
  "You are the hero of your own story.",
  "Breathe in peace, breathe out stress.",
  "You've got this, and I've got you.",
  "Stay soft in a hard world.",
  "Your peace is your priority.",
  "Life is better when you're laughing.",
  "You are someone's reason to smile.",
  "Keep blooming, no matter the season.",
  "You are braver than you believe.",
  "Good vibes only.",
  "Your mistakes don't define you.",
  "Be a voice, not an echo.",
  "The universe has your back.",
  "You are exactly where you're meant to be.",
  "Let your kindness be contagious.",
  "Every ending is a new beginning.",
  "You are a masterpiece and a work in progress.",
  "Stay curious, stay humble.",
  "Your presence is a present.",
  "Life doesn't have to be perfect to be wonderful.",
  "You are the calm in your own storm.",
  "Be the change you wish to see.",
  "Your journey is uniquely yours.",
  "Shine bright, even on cloudy days.",
  "You are magic wrapped in human.",
  "Keep showing up for yourself.",
  "The little things are the big things.",
  "You deserve rest without guilt.",
  "Your story is worth telling.",
  "Be proud of how far you've come.",
  "You radiate beautiful energy.",
  "Every day may not be good, but there's good in every day.",
  "Your best days are ahead of you.",
  "Be someone's sunshine today.",
  "You are worthy of taking up space.",
  "Life is a beautiful struggle.",
  "Your light inspires others.",
  "Keep moving forward, beautiful soul.",
  "You are not alone in this.",
  "Find beauty in the small moments.",
  "Your dreams are valid.",
  "Be kind to your future self.",
  "You are resilient and strong.",
  "Let love guide your way.",
  "Your vibe creates your life.",
  "Stay grounded, stay reaching.",
  "You are someone's answered prayer.",
  "Keep your heart open and curious.",
  "Life rewards those who show up.",
  "You are a ray of sunshine.",
  "Be gentle, be kind, be you.",
  "Your growth is inspiring.",
  "Keep watering your own grass.",
  "You are becoming who you need to be.",
  "Find your calm in the chaos.",
  "Your presence makes a difference.",
  "Be proud of your soft heart.",
  "Life is too short for bad vibes.",
  "You are worthy of happiness.",
  "Keep choosing yourself.",
  "Your soul is a garden—tend it well.",
  "Be patient, your time is coming.",
  "You are made of stardust and dreams.",
  "Find magic in the mundane.",
  "Your heart is your compass.",
  "Keep breathing, keep believing.",
  "You are a beacon of hope.",
  "Be the peace you seek.",
  "Your story has power.",
  "Life is a dance—embrace the rhythm.",
  "You are worthy just as you are.",
  "Keep spreading kindness like confetti.",
  "Your light never dims.",
  "Be grateful for the small wins.",
  "You are writing your own story.",
  "Find joy in the journey.",
  "Your presence is a gift.",
  "Keep blooming in your own time.",
  "You are loved beyond measure.",
  "Be your own biggest fan.",
  "Your soul knows the way.",
  "Life is meant to be enjoyed.",
  "You are a beautiful soul.",
  "Keep shining, keep rising.",
  "Your energy is magnetic.",
  "Be brave, be bold, be you.",
  "You are a force of nature.",
  "Find peace in the present.",
  "Your dreams deserve your belief.",
  "Keep trusting the journey.",
  "You are stronger than yesterday.",
  "Be the light in someone's darkness.",
  "Your heart is your greatest strength.",
  "Life is full of second chances.",
  "You are worthy of your dreams.",
  "Keep growing, keep glowing.",
  "Your spirit is unbreakable.",
  "Be patient with your healing.",
  "You are a walking miracle.",
  "Find beauty in imperfection.",
  "Your journey is beautiful.",
  "Keep moving at your own pace.",
  "You are deserving of all good things.",
  "Be proud of who you're becoming.",
  "Your soul is beautiful.",
  "Life is a collection of moments.",
  "You are someone's inspiration.",
  "Keep radiating positivity.",
  "Your growth is beautiful.",
  "Be kind to your wandering mind.",
  "You are a source of light.",
  "Find strength in your softness.",
  "Your heart is full of magic.",
  "Keep believing in yourself.",
  "You are exactly enough.",
  "Be gentle with your growth.",
  "Your presence matters deeply.",
  "Life rewards the patient heart.",
  "You are blooming beautifully.",
  "Keep nurturing your dreams.",
  "Your journey is just beginning.",
  "Be the love you want to feel.",
  "You are a gift to this world.",
  "Find peace in progress.",
  "Your spirit is radiant.",
  "Keep honoring your path.",
  "You are worthy of peace.",
  "Be proud of your resilience.",
  "Your light guides others home.",
  
  // New quotes (206-420+)
  "The secret of getting ahead is getting started.",
  "Your habits shape your future.",
  "Consistency beats intensity.",
  "Today's choices become tomorrow's habits.",
  "You are one decision away from a different life.",
  "Fall seven times, stand up eight.",
  "What you do every day matters more than what you do occasionally.",
  "Build habits that serve your highest self.",
  "Small daily improvements are the key to staggering results.",
  "Your routine shapes your destiny.",
  "Excellence is not an act, but a habit.",
  "The chains of habit are too light to be felt until they are too heavy to be broken.",
  "We become what we repeatedly do.",
  "Motivation gets you started; habit keeps you going.",
  "The only bad workout is the one that didn't happen.",
  "Your future is created by what you do today.",
  "Discipline is choosing between what you want now and what you want most.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Start where you are. Use what you have. Do what you can.",
  "The hardest step is the first one out the door.",
  "A little progress each day adds up to big results.",
  "Don't count the days; make the days count.",
  "Your potential is like a seed—water it daily.",
  "Every expert was once a beginner.",
  "The secret to permanent change is to focus on who you wish to become.",
  "Make each day your masterpiece.",
  "Action is the foundational key to all success.",
  "The way to get started is to quit talking and begin doing.",
  "Don't wish for it. Work for it.",
  "You don't have to be great to start, but you have to start to be great.",
  "Success is what happens after you've survived all your mistakes.",
  "Today is another chance to get better.",
  "The only person you should try to be better than is who you were yesterday.",
  "Believe you can and you're halfway there.",
  "The difference between try and triumph is just a little umph.",
  "Winners are not people who never fail, but people who never quit.",
  "Your life does not get better by chance; it gets better by change.",
  "If it doesn't challenge you, it won't change you.",
  "Strive for progress, not perfection.",
  "Today's accomplishments were yesterday's impossibilities.",
  "A goal without a plan is just a wish.",
  "Do something today that your future self will thank you for.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "What seems impossible today will be your warm-up tomorrow.",
  "Push yourself because no one else is going to do it for you.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream bigger. Do bigger.",
  "Don't be afraid to give up the good to go for the great.",
  "The only limit to your impact is your imagination and commitment.",
  "Everything you've ever wanted is on the other side of fear.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "It always seems impossible until it's done.",
  "You are never too old to set another goal or to dream a new dream.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "In the middle of difficulty lies opportunity.",
  "The mind is everything. What you think you become.",
  "Happiness is not something ready made. It comes from your own actions.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or think you can't, you're right.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only way to do great work is to love what you do.",
  "Stay hungry. Stay foolish.",
  "Innovation distinguishes between a leader and a follower.",
  "Life is what happens when you're busy making other plans.",
  "Get busy living or get busy dying.",
  "You only live once, but if you do it right, once is enough.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Never let the fear of striking out keep you from playing the game.",
  "Money and success don't change people; they merely amplify what is already there.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Not how long, but how well you have lived is the main thing.",
  "In order to write about life first you must live it.",
  "The big lesson in life is never be scared of anyone or anything.",
  "Life is really simple, but we insist on making it complicated.",
  "May you live all the days of your life.",
  "Life itself is the most wonderful fairy tale.",
  "Keep calm and carry on.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "When one door closes, another opens.",
  "The purpose of our lives is to be happy.",
  "Life is what we make it, always has been, always will be.",
  "A journey of a thousand miles begins with a single step.",
  "Peace comes from within. Do not seek it without.",
  "You must be the change you wish to see in the world.",
  "Spread love everywhere you go.",
  "The only thing we have to fear is fear itself.",
  "Ask not what your country can do for you—ask what you can do for your country.",
  "I have a dream.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "Tough times never last, but tough people do.",
  "It is during our darkest moments that we must focus to see the light.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart.",
  "It is never too late to be what you might have been.",
  "Love the life you live. Live the life you love.",
  "You have brains in your head. You have feet in your shoes.",
  "Be yourself; everyone else is already taken.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "No one can make you feel inferior without your consent.",
  "It takes courage to grow up and become who you really are.",
  "I attribute my success to this: I never gave or took any excuse.",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
  "Knowing yourself is the beginning of all wisdom.",
  "Find out who you are and do it on purpose.",
  "One of the greatest regrets in life is being what others would want you to be.",
  "To thine own self be true.",
  "What you are, you are by accident of birth; what I am, I am by myself.",
  "Never be bullied into silence. Never allow yourself to be made a victim.",
  "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.",
  "Don't compromise yourself. You are all you've got.",
  "Where there is love there is life.",
  "The only thing necessary for the triumph of evil is for good men to do nothing.",
  "True happiness is to enjoy the present, without anxious dependence upon the future.",
  "If you tell the truth, you don't have to remember anything.",
  "A friend is someone who knows all about you and still loves you.",
  "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'",
  "A day without sunshine is like, you know, night.",
  "The only impossible journey is the one you never begin.",
  "You are the universe, expressing itself as a human for a little while.",
  "Nothing is impossible. The word itself says 'I'm possible!'",
  "Light tomorrow with today.",
  "The way I see it, if you want the rainbow, you gotta put up with the rain.",
  "Do what you feel in your heart to be right.",
  "Happiness depends upon ourselves.",
  "We know what we are, but know not what we may be.",
  "Try to be a rainbow in someone's cloud.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The greatest wealth is to live content with little.",
  "He who has a why to live can bear almost any how.",
  "Well done is better than well said.",
  "An investment in knowledge pays the best interest.",
  "You can't have a better tomorrow if you're still thinking about yesterday.",
  "Wherever you go, go with all your heart.",
  "Each morning we are born again. What we do today is what matters most.",
  "Simplicity is the ultimate sophistication.",
  "Turn your wounds into wisdom.",
  "There is nothing permanent except change.",
  "The only true wisdom is in knowing you know nothing.",
  "Don't cry because it's over, smile because it happened.",
  "What we think, we become.",
  "Life shrinks or expands in proportion to one's courage.",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God.",
  "The only journey is the one within.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Every strike brings me closer to the next home run.",
  "We may encounter many defeats but we must not be defeated.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams.",
  "Security is mostly a superstition. Life is either a daring adventure or nothing.",
  "Optimism is the faith that leads to achievement.",
  "Act as if what you do makes a difference. It does.",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
  "Be faithful in small things because it is in them that your strength lies.",
  "If you cannot do great things, do small things in a great way.",
  "Never doubt that a small group of thoughtful, committed citizens can change the world.",
  "The future depends on what you do today.",
  "Service to others is the rent you pay for your room here on earth.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "I think, therefore I am.",
  "Hope is a waking dream.",
  "Quality is not an act, it is a habit.",
  "The unexamined life is not worth living.",
  "Knowing others is intelligence; knowing yourself is true wisdom.",
  "A room without books is like a body without a soul.",
  "Imagination is more important than knowledge.",
  "Education is not the filling of a pail, but the lighting of a fire.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "Real knowledge is to know the extent of one's ignorance.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "An ounce of practice is worth more than tons of preaching.",
  "The more that you read, the more things you will know.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "A candle loses nothing by lighting another candle.",
  "The wound is the place where the Light enters you.",
  "What you seek is seeking you.",
  "Let yourself be silently drawn by the strange pull of what you really love.",
  "Don't be satisfied with stories, how things have gone with others.",
  "Sell your cleverness and buy bewilderment.",
  "You were born with wings, why prefer to crawl through life?",
  "The garden of the world has no limits, except in your mind.",
  "Set your life on fire. Seek those who fan your flames.",
  "Everything in the universe is within you. Ask all from yourself.",
  "Be like a tree and let the dead leaves drop.",
  "Only from the heart can you touch the sky.",
  "Don't grieve. Anything you lose comes round in another form.",
];


export function QuotesProvider({ children }: { children: React.ReactNode }) {
  const location = useLocation();
  const [currentQuote, setCurrentQuote] = useState('');
  const [usedIndices, setUsedIndices] = useState<Set<number>>(new Set());

  const getRandomQuote = useCallback(() => {
    let availableIndices = Array.from(
      { length: COZY_QUOTES.length },
      (_, i) => i
    ).filter((i) => !usedIndices.has(i));

    // Reset if we've used all quotes
    if (availableIndices.length === 0) {
      setUsedIndices(new Set());
      availableIndices = Array.from({ length: COZY_QUOTES.length }, (_, i) => i);
    }

    const randomIndex = availableIndices[Math.floor(Math.random() * availableIndices.length)];
    setUsedIndices((prev) => new Set([...prev, randomIndex]));
    return COZY_QUOTES[randomIndex];
  }, [usedIndices]);

  const refreshQuote = useCallback(() => {
    setCurrentQuote(getRandomQuote());
  }, [getRandomQuote]);

  // Change quote on route change
  useEffect(() => {
    setCurrentQuote(getRandomQuote());
  }, [location.pathname]);

  // Initial quote
  useEffect(() => {
    if (!currentQuote) {
      setCurrentQuote(getRandomQuote());
    }
  }, []);

  return (
    <QuotesContext.Provider value={{ currentQuote, refreshQuote }}>
      {children}
    </QuotesContext.Provider>
  );
}

export function useQuotes() {
  const context = useContext(QuotesContext);
  if (context === undefined) {
    throw new Error('useQuotes must be used within a QuotesProvider');
  }
  return context;
}
